### ISSUE TITLE
IntervalTree performance

### ISSUE THREAD

**Issue by eklinger** [Breinify/brein-time-utilities#8] opened 2017-12-25 17:37 UTC
Hello,
Have you done any benchmarking on the tree? I am not quite sure what performance to expect, so let me describe my use case.
I have a map, mapping keys to interval trees. In the worst case there are about 35 keys in the map and in turn I query 35 interval trees. Each tree has ~1000 items in it. The overlap query is not cutting the tree down by much (by design), so I am fetching close to all items from each tree. Doing this sequentially and then combining all tree overlap streams into a single list is taking ~40-50ms, which seems a bit high. 
psuedo code:
`map.entrySet().stream().map(e -> e.value().overlaps(query)).flatMap(identity()).map(id -> getObject(id)).collect(toList());`
`getObject()` is just a lookup in another map to get the object from the id in the tree.
Simply changing this to a `parallelStream()` improved the performance by ~4x.
Do you have any pointers or guidance on improving the performance of the tree? Or Is this even the right approach? It is still a bit baffling to me why the sequential performance is not as high as I would imagine.
Thanks!

**Comment by eklinger** [comment] 2017-12-28 21:33
Hi again,
Can you please tell me the difference between LongInterval and Timestamp interval? They both seem to use the same underlying comparators, so does it really matter which to use in this case? You also mention that in 1.7 time series will be optimized. Can you discuss more on that and how it would be different than just storing the epoch time as a long? Thanks!

**Comment by pmeisen** [comment] 2017-12-28 22:27
Hi!

Hope you had some nice holidays. Regarding your `LongInverval` and `TimestampInterval`, we have already timezone support in the `TimestampInterval`, which the `LongInterval` does not have.  From an `IntervalTree` perspective both intervals are the same, whereby the `TimestampInterval` may utilize even more time dependent features in the future.

Regarding your performance question, let me recap what I understand. You have multiple `IntervalTree` instances, which you fire the `overlaps` method to retrieve a subset of intervals from the tree, which you then collect in a `List`. You observe, that a `parallelStream` is 4x faster than the `stream` and you are trying to understand the reason for that? First of all are we talking about the `map.entrySet().stream()`, which you replace with the `map.entrySet().parallelStream()`? Parallel streams are executed in multiple threads and depending on your system the parallelized execution may have some impact (because every `IntervalTree` can run the `overlaps` method in parallel). I would recommend to use some profiling tool to understand which method is executed faster in the parallel case.

**Comment by eklinger** [comment] 2017-12-29 20:11
Hi Phillip,
Wanted to provide an update on performance:
I was storing a unique ID in the tree and then after retrieving the overlaps I was looking up all IDs in a caffeine Map cache to get the actual object. This proved to be detrimental to performance as the cache was not able to handle the load, leading to lots of contention on the get() call. After I moved to storing the object directly in the tree the performance improved. However, I am still seeing about 14ms to fetch ~40,000 intervals and collect them to a list. There may not be much I can do to further improve this without fetching the overlaps in parallel. At least it's not obvious from the profiling. It could just be due to having to call overlaps() on 30+ tree and then add them all to a list.
Now I essentially have:

```
schedules = new ArrayList<>(count);
for (Entry<String, IntervalTree<StoreSession>> entry : allSessions.entrySet()) {
    Stream<StoreSession> overlaps = entry.getValue().overlaps(startDate.toEpochMilli(), endDate.toEpochMilli());
    schedules.addAll(overlaps.collect(Collectors.toList()));
}
```

Another area that I changed was moving from a SetIntervalCollection to ListIntervalCollection. I was seeing high contention on the spliterator for HashSet which is why I changed it. Apparently HashSets are not trivial to split, especially in parallel. 

Thanks again for such a great library!

**Comment by ben-manes** [comment] 2017-12-29 21:03
> I was storing a unique ID in the tree and then after retrieving the overlaps I was looking up all IDs in a caffeine Map cache to get the actual object. This proved to be detrimental to performance as the cache was not able to handle the load, leading to lots of contention on the get() call.

Can you stub out the calls to the cache that created contention? A cache hit should be lock-free, but a write (e.g. `compute`) would require locking the entry. It would be good to know if this is a use-case mismatch or a regression in Caffeine. Thanks!

**Comment by eklinger** [comment] 2017-12-29 21:17
Hi Ben,
I saw your performance numbers on the Caffeine site yesterday, and the large number of ops/sec was making me second guess my results, but it seems that once I removed it then the performance increased dramatically. The only setting I have is expireAfterWrite, so it seems that your discussion on re-ordering the last access list would not come into play here, is that right? The writes are relatively infrequent, about 500,000 every 5 minutes, while read was very frequent. I was also calling  cache.get() in a Comparator.compare() method (Guava's Comparators.least()) which probably also exacerbated the issue. I am designing a web app that needs to scale to 100,000 rps (not all on a single box), but the numbers of cache accesses starts adding up very quickly. Let me know how I can help.
Thanks!

**Comment by ben-manes** [comment] 2017-12-29 21:29
If you're willing and have the time to reproduce in an isolated test, then I could investigate. But I know time is hard to get so its okay if that's unreasonable.

The cache does tricks to reduce the list reordering penalty and you're right that expireAfterWrite should be minimal (only reorders on write, not read). It could be something like a bad equals/hashCode causing misses, resulting in only writes. Or there could be a bug that I am unaware of, etc. I don't think we could guess without code to debug with, unfortunately.

**Comment by eklinger** [comment] 2017-12-29 21:52
Btw, when I said contention I think I really meant latency. Not that a thread was actually blocked on the cache. I will see if I can get a stand alone test to reproduce it.

**Comment by pmeisen** [comment] 2022-05-24 01:44
Closing since this is a cache related issue and no further details were provided.

**Closed as completed by pmeisen** 2022-05-24 01:44 UTC
Labels: help wanted, question
